[project]
name = "rag-series"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "chromadb>=1.0.12",
    "docx2txt>=0.9",
    "faster-whisper>=1.1.1",
    "groq>=0.26.0",
    "instructor>=1.7.0",
    "langchain>=0.3.25",
    "langchain-community>=0.4.1,<0.4.2",
    "langchain-groq>=0.3.2",
    "langchain-chroma>=0.2.6",
    "langgraph>=0.4.7",
    "pandas>=2.2.3",
    "pydub>=0.25.1",
    "pypdf>=5.6.0",
    "python-dotenv>=1.1.0",
    "ragas>=0.4.1",
    "sentence-transformers>=4.1.0",
    "streamlit>=1.45.1",
    "tiktoken>=0.9.0",
    "transformers>=4.52.4",
    "yt-dlp>=2025.5.22",
    "protobuf>=3.20.3,<4",
    "langchain-huggingface>=1.2.2",
    "openai>=2.28.0",
]
